sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3


defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  adapter: mysql2
  database: CPGF_2016_DEV
  <<: *defaults

test: &test
  <<: *defaults

production:
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
  <<: *defaults

stage:
  adapter: mysql2
  database: CPGF_2016_DEV
  <<: *defaults